package model;
// Generated 11/08/2017 09:51:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private Integer idCuenta;
     private String nombre;
     private Set movimientos = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(String nombre) {
        this.nombre = nombre;
    }
    public Cuenta(String nombre, Set movimientos) {
       this.nombre = nombre;
       this.movimientos = movimientos;
    }
   
    public Integer getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(Integer idCuenta) {
        this.idCuenta = idCuenta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


