package model;
// Generated 11/08/2017 09:51:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoMovimiento generated by hbm2java
 */
public class TipoMovimiento  implements java.io.Serializable {


     private Integer idTipoMovimiento;
     private String nombre;
     private Set movimientos = new HashSet(0);

    public TipoMovimiento() {
    }

	
    public TipoMovimiento(String nombre) {
        this.nombre = nombre;
    }
    public TipoMovimiento(String nombre, Set movimientos) {
       this.nombre = nombre;
       this.movimientos = movimientos;
    }
   
    public Integer getIdTipoMovimiento() {
        return this.idTipoMovimiento;
    }
    
    public void setIdTipoMovimiento(Integer idTipoMovimiento) {
        this.idTipoMovimiento = idTipoMovimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


