package model;
// Generated 11/08/2017 09:51:54 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TipoMovimiento generated by hbm2java
 */
public class TipoMovimiento implements java.io.Serializable {

    private Integer idTipoMovimiento;
    private String nombre;
    private Date fechaCreacion;
    private Date fechaModificacion;

    public TipoMovimiento() {
    }

//    public TipoMovimiento(String nombre) {
//        this.nombre = nombre;
//    }
//    public TipoMovimiento(String nombre, Set movimientos) {
//       this.nombre = nombre;
////       this.movimientos = movimientos;
//    }
    public Integer getIdTipoMovimiento() {
        return this.idTipoMovimiento;
    }

    public void setIdTipoMovimiento(Integer idTipoMovimiento) {
        this.idTipoMovimiento = idTipoMovimiento;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModificacion() {
        return fechaModificacion;
    }

    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
}
