/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `account_manager` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `account_manager`;

CREATE TABLE IF NOT EXISTS `categoria_movimiento` (
  `ID_CATEGORIA_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `FECHA_MODIFICACION` date DEFAULT NULL,
  PRIMARY KEY (`ID_CATEGORIA_MOVIMIENTO`),
  UNIQUE KEY `NOMBRE` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

/*!40000 ALTER TABLE `categoria_movimiento` DISABLE KEYS */;
INSERT INTO `categoria_movimiento` (`ID_CATEGORIA_MOVIMIENTO`, `NOMBRE`, `FECHA_CREACION`, `FECHA_MODIFICACION`) VALUES
	(4, 'Alimentos', NULL, NULL),
	(5, 'Servicios Basicos', NULL, NULL),
	(6, 'Alquiler', NULL, NULL),
	(7, 'Creditos', NULL, NULL),
	(8, 'Otros', NULL, NULL);
/*!40000 ALTER TABLE `categoria_movimiento` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `cuenta` (
  `ID_CUENTA` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `FECHA_MODIFICACION` date DEFAULT NULL,
  PRIMARY KEY (`ID_CUENTA`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*!40000 ALTER TABLE `cuenta` DISABLE KEYS */;
INSERT INTO `cuenta` (`ID_CUENTA`, `NOMBRE`, `FECHA_CREACION`, `FECHA_MODIFICACION`) VALUES
	(3, 'Cuenta BCR', NULL, NULL),
	(4, 'Cuenta BNCR', NULL, NULL);
/*!40000 ALTER TABLE `cuenta` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `movimiento` (
  `ID_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `DETALLE` varchar(255) NOT NULL,
  `MONTO` double NOT NULL,
  `FECHA_MOVIMIENTO` date NOT NULL,
  `FECHA_CONTABLE` date DEFAULT NULL,
  `CATEGORIA_MOVIMIENTO` int(11) NOT NULL,
  `TIPO_MOVIMIENTO` int(11) NOT NULL,
  `CUENTA` int(11) NOT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `FECHA_MODIFICACION` date DEFAULT NULL,
  PRIMARY KEY (`ID_MOVIMIENTO`),
  KEY `FK_MOVIMIENTO_categoria_movimiento` (`CATEGORIA_MOVIMIENTO`),
  KEY `FK_MOVIMIENTO_tipo_movimiento` (`TIPO_MOVIMIENTO`),
  KEY `FK_movimiento_estado_movimiento` (`CUENTA`),
  CONSTRAINT `FK_MOVIMIENTO_categoria_movimiento` FOREIGN KEY (`CATEGORIA_MOVIMIENTO`) REFERENCES `categoria_movimiento` (`ID_CATEGORIA_MOVIMIENTO`),
  CONSTRAINT `FK_MOVIMIENTO_tipo_movimiento` FOREIGN KEY (`TIPO_MOVIMIENTO`) REFERENCES `tipo_movimiento` (`ID_TIPO_MOVIMIENTO`),
  CONSTRAINT `FK_movimiento_cuenta` FOREIGN KEY (`CUENTA`) REFERENCES `cuenta` (`ID_CUENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40000 ALTER TABLE `movimiento` DISABLE KEYS */;
/*!40000 ALTER TABLE `movimiento` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `parametro` (
  `ID_PARAMETRO` int(11) NOT NULL AUTO_INCREMENT,
  `LLAVE` varchar(100) NOT NULL,
  `VALOR` varchar(20) NOT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `FECHA_MODIFICACION` date DEFAULT NULL,
  PRIMARY KEY (`ID_PARAMETRO`),
  UNIQUE KEY `llave` (`LLAVE`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='Tabla para parametros';

/*!40000 ALTER TABLE `parametro` DISABLE KEYS */;
INSERT INTO `parametro` (`ID_PARAMETRO`, `LLAVE`, `VALOR`, `FECHA_CREACION`, `FECHA_MODIFICACION`) VALUES
	(2, 'categoria_movimiento_default', '8', NULL, NULL),
	(3, 'tipo_movimiento_gasto', '2', NULL, NULL),
	(4, 'tipo_movimiento_ingreso', '3', NULL, NULL);
/*!40000 ALTER TABLE `parametro` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tipo_movimiento` (
  `ID_TIPO_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  `FECHA_CREACION` date DEFAULT NULL,
  `FECHA_MODIFICACION` date DEFAULT NULL,
  PRIMARY KEY (`ID_TIPO_MOVIMIENTO`),
  UNIQUE KEY `NOMBRE` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*!40000 ALTER TABLE `tipo_movimiento` DISABLE KEYS */;
INSERT INTO `tipo_movimiento` (`ID_TIPO_MOVIMIENTO`, `NOMBRE`, `FECHA_CREACION`, `FECHA_MODIFICACION`) VALUES
	(2, 'Gasto', NULL, NULL),
	(3, 'Ingreso', NULL, NULL);
/*!40000 ALTER TABLE `tipo_movimiento` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
