
DROP DATABASE IF EXISTS `account _manager`;
CREATE DATABASE IF NOT EXISTS `account_manager`;
USE `account_manager`;


CREATE TABLE IF NOT EXISTS `categoria_movimiento` (
  `ID_CUENTA_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_CUENTA_MOVIMIENTO`),
  UNIQUE KEY `NOMBRE` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


INSERT INTO `categoria_movimiento` (`ID_CUENTA_MOVIMIENTO`, `NOMBRE`) VALUES
  (4, 'Alimentos'),
  (6, 'Alquiler'),
  (7, 'Creditos'),
  (8, 'Otros'),
  (5, 'Servicios Basicos');

CREATE TABLE IF NOT EXISTS `tipo_movimiento` (
  `ID_TIPO_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_TIPO_MOVIMIENTO`),
  UNIQUE KEY `NOMBRE` (`NOMBRE`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

INSERT INTO `tipo_movimiento` (`ID_TIPO_MOVIMIENTO`, `NOMBRE`) VALUES
  (2, 'Gasto'),
  (3, 'Ingreso');

CREATE TABLE IF NOT EXISTS `cuenta` (
  `ID_CUENTA` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_CUENTA`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS `movimiento` (
  `ID_MOVIMIENTO` int(11) NOT NULL AUTO_INCREMENT,
  `DETALLE` varchar(255) NOT NULL,
  `MONTO` double NOT NULL,
  `FECHA_MOVIMIENTO` date NOT NULL,
  `FECHA_CONTABLE` date NOT NULL,
  `CATEGORIA_MOVIMIENTO` int(11) NOT NULL,
  `TIPO_MOVIMIENTO` int(11) NOT NULL,
  `CUENTA` int(11) NOT NULL,
  PRIMARY KEY (`ID_MOVIMIENTO`),
  KEY `FK_MOVIMIENTO_categoria_movimiento` (`CATEGORIA_MOVIMIENTO`),
  KEY `FK_MOVIMIENTO_tipo_movimiento` (`TIPO_MOVIMIENTO`),
  KEY `FK_movimiento_estado_movimiento` (`CUENTA`),
  CONSTRAINT `FK_MOVIMIENTO_categoria_movimiento` FOREIGN KEY (`CATEGORIA_MOVIMIENTO`) REFERENCES `categoria_movimiento` (`ID_CUENTA_MOVIMIENTO`),
  CONSTRAINT `FK_MOVIMIENTO_tipo_movimiento` FOREIGN KEY (`TIPO_MOVIMIENTO`) REFERENCES `tipo_movimiento` (`ID_TIPO_MOVIMIENTO`),
  CONSTRAINT `FK_movimiento_cuenta` FOREIGN KEY (`CUENTA`) REFERENCES `cuenta` (`ID_CUENTA`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

